# in .cargo/config.toml
# The feature 'build-std' ==> It allows to recompile core and other standard library crates on demand, 
# instead of using the precompiled versions shipped with the 
# Rust installation, it is because the own target is used, 
# not something like 'x86_64-unknown-linux-gnu'


# # recomplie functions like 'memcpy', 'memset', 'memcmp'
[unstable]
build-std-features = ["compiler-builtins-mem"] 
build-std = ["core", "compiler_builtins"]

# default target 
[build]
target = "x86_64-blog_os.json"